### ISSUE TITLE
Improve README: Explain the screenshots

### ISSUE THREAD

**Issue by sesam** [kalaspuffar/wordpress-sqrl-login#41]
The README.md has some screenshots that could be explained more. I could make a PR on this, but would need some help understanding the text "Will look for QR login in 3" (or 2 or 1). Maybe that is just example texts used to distinguish the screenshots?
And what about the Play / Windows phone links, is that links to download the "SQRL Login" mobile app perhaps?

**Comment by kalaspuffar** [comment]
Hi @sesam 

The text "Will look for QR login in 3....2...1" is actually a countdown until we talk to the system and see if there is an update on the login status. You could implement this in multiple ways and if you had more control than a wordpress-plugin you might opt to do this with websockets.

But when a mobile client logs you in it changes the status on the server to logged in. The webpage does not get notified about this change but periodicly it will poll the server for update in order to log you in. I though it would be a good thing for the user to see the count down so they don't wonder why the site hasn't logged them in yet.

The buttons for Play and Windows are there to give you links to Google Play for download and also a link to the reference Windows client from Steve.

Best regards
Daniel
